#!/usr/bin/env python3
"""Private helper for flash.sh: immutable inputs and whole-flash verification."""
import hashlib
import json
import os
from pathlib import Path
import shutil
import struct
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
from fw_package import manifest, validate

FLASH_SIZE = 0x100000
SECTORS = [0, 0x4000, 0x8000, 0xC000, 0x10000, 0x20000,
           0x40000, 0x60000, 0x80000, 0xA0000, 0xC0000, 0xE0000, 0x100000]
BOOT = ("bootloader.bin", 0)
APP = [("image-manifest.bin", 0xC000), ("application.ota.bin", 0x10000)]


def images_for(mode):
    return ([BOOT] if mode in ('boot', 'all') else []) + (APP if mode in ('app', 'all') else [])


def digest(data):
    return hashlib.sha256(data).hexdigest()


def require(condition, message):
    if not condition:
        raise ValueError(message)


def read_dump(session, name):
    data = (session / name).read_bytes()
    require(len(data) == FLASH_SIZE, f"{name}: sauvegarde incomplète")
    return data


def prepare(session, mode, profile):
    # Session paths are generated by mktemp, relative to the repository, Tcl-safe.
    require(all(c.isalnum() or c in '/-_' for c in str(session)), "Chemin de session invalide")
    require(mode in ('app', 'boot', 'all') and profile in ('debug', 'release'),
            'Sélection de flash invalide')
    build = ROOT / 'build' / profile
    selected = images_for(mode)
    if mode in ('app', 'all'):
        app = (build / 'application.ota.bin').read_bytes()
        validate(app)
        require((build / 'image-manifest.bin').read_bytes() == manifest(app),
                'Manifeste incompatible avec l’application')
    if mode in ('boot', 'all'):
        boot = (build / 'bootloader.bin').read_bytes()
        require(8 <= len(boot) <= 0x4000, 'Taille du bootloader incorrecte')
        sp, pc = struct.unpack_from('<II', boot)
        require(0x20000000 < sp <= 0x20020000 and sp % 8 == 0
                and pc & 1 and 0x08000000 <= pc < 0x08000000 + len(boot),
                'Vecteurs du bootloader incorrects')
    for name, _ in selected:
        shutil.copy2(build / name, session / name)
    symbols = {}
    if mode != 'boot':
        shutil.copy2(build / 'ZHONX_II_M4.elf', session)
        for line in subprocess.check_output(
                ['arm-none-eabi-nm', str(session / 'ZHONX_II_M4.elf')], text=True).splitlines():
            fields = line.split()
            if len(fields) == 3:
                symbols[fields[2]] = int(fields[0], 16)
        ticks, sequence = symbols['os_context'] + 4, symbols['scan'] + 4
    header = 'source [find interface/stlink.cfg]\ntransport select hla_swd\n'
    serial = os.environ.get('STLINK_SERIAL', '')
    if serial:
        header += f'adapter serial {serial}\n'
    header += f'''source [find target/stm32f4x.cfg]
adapter speed {os.environ.get('SWD_KHZ', '1000')}
gdb_port disabled
tcl_port disabled
telnet_port disabled
init
reset halt
if {{([lindex [read_memory 0xe0042000 32 1] 0] & 0xfff) != 0x413}} {{ error "MCU inattendu" }}
if {{[lindex [read_memory 0x1fff7a22 16 1] 0] != 1024}} {{ error "Flash attendue : 1 Mio" }}
'''
    (session / 'backup.cfg').write_text(header + f'dump_image {session}/pre-flash.bin 0x08000000 0x100000\nshutdown\n')
    program = header
    # Application first, then its committed manifest, then bootloader. No mass erase.
    for name, offset in reversed(selected):
        program += f'flash write_image erase {session}/{name} {0x08000000 + offset:#x} bin\n'
        program += f'verify_image {session}/{name} {0x08000000 + offset:#x} bin\n'
    program += f'dump_image {session}/post-flash.bin 0x08000000 0x100000\nshutdown\n'
    (session / 'program.cfg').write_text(program)
    startup = header + '''reset run
sleep 2000
halt
echo "VTOR [read_memory 0xe000ed08 32 1]"
echo "CFSR_HFSR [read_memory 0xe000ed28 32 2]"
echo "GPIOA_ODR [read_memory 0x40020014 32 1]"
if {([lindex [read_memory 0x40020014 32 1] 0] & 0x10c) != 0x100} { error "Moteurs non desactives au repos" }
'''
    if mode != 'boot':
        startup += f'''
if {{[lindex [read_memory 0xe000ed08 32 1] 0] != 0x08010000}} {{ error "Application non demarree" }}
if {{[lindex [read_memory 0xe000ed28 32 1] 0] != 0 || [lindex [read_memory 0xe000ed2c 32 1] 0] != 0}} {{ error "Defaut processeur" }}
if {{[lindex [read_memory {symbols['fault']:#x} 32 1] 0] != 0 || [lindex [read_memory {symbols['active']:#x} 32 1] 0] != 0}} {{ error "Etat mouvement inattendu" }}
set ticks_before [lindex [read_memory {ticks:#x} 32 1] 0]
set scan_before [lindex [read_memory {sequence:#x} 32 1] 0]
resume
sleep 250
halt
set ticks_after [lindex [read_memory {ticks:#x} 32 1] 0]
set scan_after [lindex [read_memory {sequence:#x} 32 1] 0]
echo "Ticks $ticks_before -> $ticks_after ; capteurs $scan_before -> $scan_after"
if {{$ticks_after == $ticks_before || $scan_after == $scan_before}} {{ error "Tick ou acquisition capteurs bloques" }}
'''
    else:
        startup += '''
if {[lindex [read_memory 0xe000ed28 32 1] 0] != 0 || [lindex [read_memory 0xe000ed2c 32 1] 0] != 0} { error "Defaut processeur" }
'''
    startup += '''
resume
shutdown
'''
    (session / 'startup.cfg').write_text(startup)
    commit = subprocess.run(['git', 'rev-parse', 'HEAD'], capture_output=True, text=True)
    return {'status': 'prepared', 'mode': mode, 'profile': profile,
            'source_commit': commit.stdout.strip(),
            'images': {name: {'sha256': digest((session / name).read_bytes()),
                              'address': hex(0x08000000 + off)} for name, off in selected}}


def verify(session, mode='all'):
    before = read_dump(session, 'pre-flash.bin')
    after = read_dump(session, 'post-flash.bin')
    expected = bytearray(before)
    erased = set()
    for name, offset in images_for(mode):
        data = (session / name).read_bytes()
        for start, end in zip(SECTORS, SECTORS[1:]):
            if start < offset + len(data) and end > offset:
                erased.add((start, end))
    require(not any(start in (0x4000, 0x8000) or start >= 0x80000
                    for start, _ in erased), 'Effacement hors zone autorisée')
    for start, end in erased:
        expected[start:end] = b'\xff' * (end - start)
    for name, offset in images_for(mode):
        data = (session / name).read_bytes()
        expected[offset:offset + len(data)] = data
    require(after == expected, 'Relecture différente de l’image attendue (y compris zones préservées)')
    return {'status': 'flash_verified', 'post_flash_sha256': digest(after),
            'erased_ranges': [[hex(0x08000000 + a), hex(0x08000000 + b)]
                              for a, b in sorted(erased)],
            'untouched_flash_verified': True}


def main():
    action, directory, *selection = sys.argv[1:]
    session = Path(directory)
    report_path = session / 'report.json'
    report = json.loads(report_path.read_text()) if report_path.exists() else {}
    if action == 'prepare':
        require(len(selection) == 2, 'Indiquer mode et profil')
        report = prepare(session, *selection)
    elif action == 'backup':
        data = read_dump(session, 'pre-flash.bin')
        checksum = digest(data)
        (session / 'pre-flash.bin.sha256').write_text(f'{checksum}  pre-flash.bin\n')
        report.update(status='backup_verified', pre_flash_sha256=checksum)
    elif action == 'verify':
        require(report.get('status') == 'backup_verified', 'Sauvegarde non vérifiée')
        require(digest(read_dump(session, 'pre-flash.bin')) == report['pre_flash_sha256'],
                'Sauvegarde modifiée depuis sa validation')
        report.update(verify(session, report['mode']))
    elif action == 'complete':
        require(report.get('status') == 'flash_verified', 'Flash non vérifiée')
        report.update(status='startup_verified' if report['mode'] != 'boot' else 'reset_verified')
    else:
        raise ValueError(f'Action inconnue : {action}')
    report_path.write_text(json.dumps(report, indent=2) + '\n')


if __name__ == '__main__':
    main()
